### ISSUE TITLE
Add is_distinct function

### ISSUE THREAD

**Issue by michaelmcd18** [metrumresearchgroup/mrgmisc#24]
```
is_distinct <- function(.df, .cols_unique) {
  
  .distinct_df <- 
    .df %>% 
    select(all_of(.cols_unique)) %>% 
    distinct()
  
  assertthat::assert_that(
    nrow(.distinct_df) == nrow(.df)
  )
  
}
```

**Comment by andersone1** [comment]
slightly more finalized version:

```
is_distinct <- function(.df, .cols) {
  
  .distinct_df <- 
    .df %>% 
    select(all_of(.cols)) %>% 
    distinct()
  
   nrow(.distinct_df) == nrow(.df)
  
}
```

**Comment by michaelmcd18** [comment]
@andersone1 

I don't think I'm fully appreciating this function, what would be some use cases for this? 

This looks like it's checking if a group of columns are completely distinct in a dataframe, which using this to check NUM comes to mind. But I'm not sure of other common columns that could use this?

**Comment by andersone1** [comment]
@michaelmcd18 i am thinking of it as just a handy function to check for duplicates throughout a DA, eg:


`is_distinct(out$tv$pc, c("USUBJID", "DATETIME"))`

**Comment by michaelmcd18** [comment]
@andersone1 Ah I got it now, thanks for the explanation, that'd definitely be useful!
