### ISSUE TITLE
Obs summary function

### ISSUE THREAD

**Issue by andersone1** [metrumresearchgroup/mrgmisc#32]
![image](https://github.com/metrumresearchgroup/mrgmisc/assets/28537780/45a8d29e-8f48-45cf-9126-cfb89e2156e2)

**Comment by michaelmcd18** [comment]
Bringing this over from slack discussion:

`Subject needs to have at least 1 quantifiable (non-BLQ) observation to count as having pk`

`function would need to identify the PK observation rows and also confirm there is no BLQ as well`

`could use a leading group_by or filter to just get down to PK` (to remove complexity from function)
